#!/bin/sh

# MIT license (c) 2024 https://github.com/slowpeek
# Homepage: https://github.com/slowpeek/mc-squashfs
# About: SquashFS plugin for Midnight Commander

awk_format_list=$(cat <<'EOF'
# The first line is the "root" dir, skip it
NR>1 {
    o = 0

    # Special case: block/character device with "size" column matching /major, +minor/
    if (substr($3, length($3)) == ",") {
       # Make it "major,minor"
       $3 = $3 $4

       # Step over the "minor" field in the following
       o = 1
    }

    # Split "user/group"
    split($2, owner, "/")

    # Split "YYYY-MM-DD"
    split($(4+o), date, "-")

    # Slash in "user/group"
    i = index($0, "/")
    # Leading slash in the path
    i += index(substr($0, i+1), "/")

    # The path part
    s = substr($0, i)

    if (substr($0, 1, 1) == "l") {
        s1=s
        if (gsub("->", "", s1) > 1) {
            # Ambiguity: either the link or its target contains q(->) in
            # addition to the link/target delimiter
            next
        }
    } else if (index(s, "->")) {
        # Ambiguity: not a symlink, but there is q(->)
        next
    }

    print $1, 1, owner[1], owner[2], $3, date[2] "-" date[3] "-" date[1], $(5+o), s
}
EOF
)

if ! command -v unsquashfs >/dev/null; then
    echo 'unsquashfs is not installed (squashfs-tools package)' >&2
    exit 1
fi

cmd=$1
shift

case "$cmd" in
    list)
        temp_ls=$(mktemp "${MC_TMPDIR:-/tmp}"/mc-usqfs.XXXXXX) || exit
        # shellcheck disable=SC2064
        trap "rm -f '${temp_ls}'" EXIT

        unsquashfs -d '' -lls "$1" > "$temp_ls" || exit

        awk "$awk_format_list" < "$temp_ls"
        exit ;;

    copyout)
        unsquashfs -cat "$1" "$2" > "$3" 2>/dev/null
        exit ;;

    *)
        exit 1 ;;
esac
